---
title: "Process carbonate budgets data with reefbudgetR"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, eval = FALSE)
knitr::opts_knit$set(root.dir = 'T:/Oceanography/Carbonate Budgets/NCEI package')

library(reefbudgetR)
library(tidyverse)
library(dplyr)


```

```{r load_data}
# Set working directory containing data
setwd("T:/Oceanography/Carbonate Budgets/NCEI package/ESD_CarbBudget_MARIAN_2022")

# Load benthic, urchin, and fish data
benthic_data <- read.csv("ESD_CarbBudget_MARIAN_2022/Data/ESD_CarbBudget_Benthic_MARIAN_2022.csv", na = "", check.names = FALSE)

urchin_data <- read.csv("ESD_CarbBudget_MARIAN_2022/Data/ESD_CarbBudget_Urchins_MARIAN_2022.csv", na = "", check.names = FALSE)

fish_data_belt <- read.csv("ESD_CarbBudget_MARIAN_2022/Data/ESD_CarbBudget_Fixed_Belt_MARIAN_2022.csv", na = "", check.names = FALSE)

fish_data_spc <- read.csv("ESD_CarbBudget_MARIAN_2022/Data/ESD_CarbBudget_SPC_MARIAN_2022.csv", na = "", check.names = FALSE)


```

```{r process_prod}

#### Process benthic data by method type

# Process IPRB benthic data
prod_iprb <- process_prod(
  data = benthic_data[benthic_data$CB_METHOD == "IPRB", ],
  method_name = "IPRB"
)

# Process chords benthic data
prod_chords <- process_prod(
  data = benthic_data[benthic_data$CB_METHOD == "Chords", ],
  method_name = "Chords"
)

# Process SfM benthic data
prod_sfm <- process_prod(
  data = benthic_data[benthic_data$CB_METHOD == "SfM", ],
  method_name = "SfM"
)

# Combine site-level production data back together
prod_site <- bind_rows(
  prod_iprb$summary_site,
  prod_chords$summary_site,
  prod_sfm$summary_site
)

```

```{r process_urchins}

#### Process urchin data by method type

# Process IPRB urchin data
urch_iprb <- process_urchins(
  data = urchin_data[urchin_data$CB_METHOD == "IPRB", ],
  method_name = "IPRB"
)

# Process chords urchin data
urch_chords <- process_urchins(
  data = urchin_data[urchin_data$CB_METHOD == "Chords", ],
  method_name = "Chords"
)


# Combine site-level urchin erosion data back together
urch_site <- bind_rows(urch_iprb$site_erosion,
                                 urch_chords$site_erosion)

```


```{r process_parrotfish}

fish_belt <- process_fish(
  data = fish_data_belt, 
  method = "IPRB",
  dbase_type = "Kindinger", 
  full_summary = TRUE)

fish_fixed_spc <- process_fish(
  data = fish_data_spc, 
  method = "Fixed SPC",
  dbase_type = "Kindinger", 
  sites_associated = "OAH")

fish_strs_spc <- process_fish(
  data = fish_data_spc, 
  method = "StRS SPC",
  dbase_type = "Kindinger", 
  sites_associated = "OAH")


fish_site_belt <- fish_belt$fish_erosion_site 

# If Excavator functional group is missing:
fish_fixed_spc <- fish_fixed_spc %>%
                    add_column(FISH_BIOMASS_KG_HA_EXCAVATOR_L95 = 0,
                               FISH_BIOMASS_KG_HA_EXCAVATOR_MEAN = 0,
                               FISH_BIOMASS_KG_HA_EXCAVATOR_SD = 0,
                               FISH_BIOMASS_KG_HA_EXCAVATOR_SE = 0,
                               FISH_BIOMASS_KG_HA_EXCAVATOR_U95 = 0,
                               FISH_DENSITY_ABUNDANCE_HA_EXCAVATOR_L95 = 0,
                               FISH_DENSITY_ABUNDANCE_HA_EXCAVATOR_MEAN = 0,
                               FISH_DENSITY_ABUNDANCE_HA_EXCAVATOR_SD = 0,
                               FISH_DENSITY_ABUNDANCE_HA_EXCAVATOR_SE = 0,
                               FISH_DENSITY_ABUNDANCE_HA_EXCAVATOR_U95 = 0,
                               FISH_EROSION_KG_M2_YR_EXCAVATOR_L95 = 0,
                               FISH_EROSION_KG_M2_YR_EXCAVATOR_MEAN = 0,
                               FISH_EROSION_KG_M2_YR_EXCAVATOR_SD = 0,
                               FISH_EROSION_KG_M2_YR_EXCAVATOR_SE = 0,
                               FISH_EROSION_KG_M2_YR_EXCAVATOR_U95 = 0) %>%
                      select(REGION:FISH_BIOMASS_KG_HA_ALL_U95, FISH_BIOMASS_KG_HA_EXCAVATOR_L95:FISH_BIOMASS_KG_HA_EXCAVATOR_U95, FISH_BIOMASS_KG_HA_OTHER_L95:FISH_BIOMASS_KG_HA_SCRAPER_U95, 
                             FISH_DENSITY_ABUNDANCE_HA_ALL_L95:FISH_DENSITY_ABUNDANCE_HA_ALL_U95, FISH_DENSITY_ABUNDANCE_HA_EXCAVATOR_L95:FISH_DENSITY_ABUNDANCE_HA_EXCAVATOR_U95, 
                             FISH_DENSITY_ABUNDANCE_HA_OTHER_L95:FISH_DENSITY_ABUNDANCE_HA_SCRAPER_U95, FISH_EROSION_KG_M2_YR_ALL_L95:FISH_EROSION_KG_M2_YR_ALL_U95, 
                             FISH_EROSION_KG_M2_YR_EXCAVATOR_L95:FISH_EROSION_KG_M2_YR_EXCAVATOR_U95, FISH_EROSION_KG_M2_YR_OTHER_L95:FISH_EROSION_KG_M2_YR_SCRAPER_U95)

fish_site_belt
fish_fixed_spc
fish_strs_spc

oahu_kindinger <- rbind(fish_site_belt, fish_fixed_spc, fish_strs_spc)
oahu_iprb <- rbind(fish_site_belt, fish_fixed_spc, fish_strs_spc)


```

```{r process_net}

# Process net production data
net_site = process_net(
  prod = prod_site,
  urch = urch_site,
  fish = fish_site
)


```
